# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - shared

  mysql-adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - shared

networks:
  shared:
    external:
      name: shared